#http://ip/mywebapplication
version: '3.2'

services:
  builder1:
    build:
      context: builder1/
    volumes:
      - type: volume  
        source: builder1
        target: /home/user/share 

  prod1:
    build:
      context: prod1/
    volumes: 
      - type: volume
        source: builder1
        target: /usr/local/tomcat/webapps
    ports: 
      - "80:8080"
    depends_on: 
      - builder1
volumes: 
  builder1: